# Generated by Django 3.0.7 on 2021-03-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('designation', models.CharField(max_length=32)),
                ('facebook_url', models.URLField(max_length=255)),
                ('Instagram_url', models.URLField(max_length=255)),
                ('linkedin_url', models.URLField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
